### ISSUE TITLE
Code Help

### ISSUE THREAD

**Issue by IsaacBentata** [harsh19/ChessCommentaryGeneration#1]
Hi,

Thank you for this amazing project.

I have currently extracted all my data and split into the .en files etc. for validation test and training. I now want to split it into the different categories but I'm unsure of how to work your code for the SVM. Will you be updating this?

I am using the commentary as part of a dataset for a sentiment analysis research project, meaning we only want to focus on quality moves. Thus, being able to retrieve the quality moves would be great.

Thanks,

**Comment by harsh19** [comment]
Hi, thanks for showing interest in our work. Svm uses some tagged data, and due to the nature of tagged data, we cannot share it through the github repo. Could you please send an email to jharsh@andrew.cmu.edu and I can then help you to get the final files ?
