### ISSUE TITLE
Can you provide processed dataset to me? 

### ISSUE THREAD

**Issue by sawalai** [harsh19/ChessCommentaryGeneration#3]
I follow the /Data/crawler/README to run the code, but cannot run the code in /Code/chess_features/.
Can you provide processed dataset to me? My e-mail is: yamapi0409cow@gmail.com
Thank you very much!

**Comment by sawalai** [comment]
Can you provide annotation2.tsv to me?
Thank you very much.

**Comment by harsh19** [comment]
Had shared the data with you over email earlier. Closing the issue.  Let us know if you face any further issue.
